# Site settings
title: Keat's
author: Keat
#author_avatar:
email: keat.png@gmail.com
description: Blog about whatever.
#baseurl: "" # optional
url: "https://keatosis.github.io"
#twitter_username: foo_bar
#github_username: foo_bar
#github_repo: foo_bar/foo_bar.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
